#!/bin/sh -e

optimisation=3

if command -v musl-gcc >/dev/null; then
  compiler=musl-gcc
else
  compiler=gcc
fi

warnings="-Wall -Wfatal-errors"
compiler_options="-std=c17 -pedantic-errors -D_POSIX_C_SOURCE=200809L -D_FILE_OFFSET_BITS=64 $warnings -fno-common -fno-math-errno -O$optimisation"

prefix=exe/compiled
mkdir -p "$prefix"

for name in drop-long-lines files-filter replace-string rate lines-filter splice is-empty-directory unique-name line-length stemname dcat rename-lowercase group
do
  "$compiler" $compiler_options "src/$name.c" -o "$prefix/$name"
  chmod +x "$prefix/$name"
done

#name=stdio-command-gui
#$compiler $compiler_options src/$name.c -o $prefix/$name.c $(pkg-config --cflags --libs gtk4 gio-2.0)
